
server:
  port: 8764
eureka:
  instance:
    hostname:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-ribbon-client
ribbon:
  eager-load:
    enabled: false

feign:
  hystrix:
    enabled: true

